DoctorAppointment/Models/Appointment.cs
using System;
using System.ComponentModel.DataAnnotations;
namespace DoctorAppointment.Models
{
    public class Appointment
    {
        [Key]
        public int AppointmentID { get; set; }
        public string AppointmentDate { get; set; } 
        public int PatID { get; set; }
        public int DocID { get; set; }
        public string AppointmentDay { get; set; }

    }
}

DoctorAppointment/Controllers/AppointmentController.cs
using DoctorAppointment.Data;
using DoctorAppointment.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Web;

namespace DoctorAppointment.Controllers
{
    public class AppointmentController : Controller
    {
        private readonly MyContext _context;
        public AppointmentController(MyContext context) 
        {
            _context = context;
        }
        public IActionResult BookAppointment()
        {
            var departments =   _context.tblDepartments.Select(d => d.DepartmentName).Distinct().ToList();
            ViewBag.Departments = departments;
            return View();
        }
        
        public IActionResult DepartmentbyID(int DepartId)
        {
            return View(_context.tblDoctor.Where(a => a.DepartmentId == DepartId).ToList());
        }

        [HttpPost]
        public IActionResult Add(Appointment ap)
        {
            _context.tblAppointment.Add(ap);
            _context.SaveChanges();
            return RedirectToAction("BookAppointment", "Appointment");
           // return View(_context.tblDoctor.Where(a => a.DepartmentId == DepartId).ToList());
        }

        public IActionResult Check(string department)
        {
            // Retrieve the list of appointments from your data source,
            // filtered by the selected department (if any)

            //  IQueryable<DocotorInfo> appointments = _context.tblDoctor;
            //if (!string.IsNullOrEmpty(department))
            //{
            //   // appointments = appointments.Where(a => a.Department == department);
            //}

            // Retrieve the department object for the selected department
            var selectedDepartment = _context.tblDepartments
                .Include(d => d.Doctors)
                .FirstOrDefault(d => d.DepartmentName == department);

            // Retrieve the list of doctors for the selected department
            var doctors = selectedDepartment?.Doctors?.ToList();

            // Create a view model to pass the appointments and department
            // information to the view
            //var viewModel = new AppointmentViewModel
            //{
            //    Appointments = doctors.ToList(),
            //    Department = department,
            //    Doctors = doctors
            //};

            // Pass the view model to the view
            // return View(viewModel);
            return View(doctors);
       }

        public IActionResult Create()
        {
           // var departments = _context.tblDepartments.Select(d => d.DepartmentName).Distinct().ToList();
           // ViewBag.Departments = departments;
            return View();
        }

        public IActionResult BookApppointmentByPatient()
        {
          var patID=   HttpContext.Session.GetString("Patient");
           // dateofweek
           // HttpContext.Session.GetString("dateofweek");
            HttpContext.Session.SetString("PtID", patID); ;
            //var Getrole = Context.Session.GetString("Patient");
            // var departments = _context.tblDepartments.Select(d => d.DepartmentName).Distinct().ToList();
            // ViewBag.Departments = departments;
            return View();
        }

    }
}

DoctorAppointment/Controllers/DoctorInfoes1Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DoctorAppointment.Data;
using DoctorAppointment.Models;
using DoctorAppointment.Models.Data.Repositories;
using DoctorAppointment.Services;
using DoctorAppointment.Data.Repositories;
using Microsoft.AspNetCore.Http;

namespace DoctorAppointment.Controllers
{
    public class DoctorInfoes1Controller : Controller
    {
        private readonly MyContext _context;
        private readonly IMailService _service;
        private readonly IUserLogin _user1;
        // private readonly IDepartmentRepository _repository;
        public DoctorInfoes1Controller(MyContext context, IMailService service, IUserLogin user1)
        {
            _context = context;
            _service = service;
            _user1 = user1;
            //  _repository = rep;   //Dependecy Injenction
        }

        // GET: DoctorInfoes1
        [CustomAuthorizeAttribute("Admin", "Doctor")]
        public async Task<IActionResult> Index()
        {

            // return View(await _context.tblDoctor.ToListAsync());
            //  string userEmail = User.Identity.Name; // get the email of the logged-in user
            string UserRole = HttpContext.Session.GetString("Role");
            ViewBag.Role = UserRole;
            if(UserRole =="Doctor") { 
            string userEmail = HttpContext.Session.GetString("UserEmail");
                var doctor = _context.tblDoctor.Where(p => p.EmailAddress == userEmail);
               // var doctor = await _context.tblDoctor.FirstOrDefaultAsync(d => d.EmailAddress == userEmail);
            //var qry = (from c in _context.tblDoctor
            //           join k in _context.tblDepartments
            //           on c.DepartmentId equals k.DepartmentId
            //           where c.EmailAddress == userEmail // filter by doctor's email
            //           select new DoctorInfo
            //           {
            //               First_Name = c.First_Name,
            //               Last_Name = c.Last_Name,
            //               DepartmentId = c.DepartmentId,
            //               EmailAddress = c.EmailAddress,
            //               ContactNumber = c.ContactNumber,
            //               HomeAddress = c.HomeAddress,
            //               IsAvailable = c.IsAvailable,
            //               DoctorFee = c.DoctorFee,
            //               Department = k
            //           }).ToList();
            return View(doctor);
            }

            else {

                //Linq= Language Integrated Query
                //var qry = (from c in _context.tblDoctor
                //           join k in _context.tblDepartments
                //           on c.DepartmentId equals k.DepartmentId
                //           select new DoctorInfo
                //           {
                //               First_Name = c.First_Name,
                //               Last_Name = c.Last_Name,
                //               DepartmentId = c.DepartmentId, //Mazeed field add ki ja skte ha
                //                                              //   AvailableDates=c.AvailableDates,
                //               EmailAddress = c.EmailAddress,
                //               ContactNumber = c.ContactNumber,
                //               HomeAddress = c.HomeAddress,
                //               IsAvailable = c.IsAvailable,
                //               DoctorFee = c.DoctorFee,
                //               Department = k

                //           }).ToList();
                //return View(qry);

                var qry = (from c in _context.tblDoctor
                           join k in _context.tblDepartments
                           on c.DepartmentId equals k.DepartmentId into department
                           from d in department.DefaultIfEmpty()
                           select new DoctorInfo
                           {
                               First_Name = c.First_Name,
                               Last_Name = c.Last_Name,
                               DepartmentId = c.DepartmentId,
                               EmailAddress = c.EmailAddress,
                               ContactNumber = c.ContactNumber,
                               HomeAddress = c.HomeAddress,
                               IsAvailable = c.IsAvailable,
                               DoctorFee = c.DoctorFee,
                               Department = d
                           }).ToList();
                return View(qry);



            }










        }

        // GET: DoctorInfoes1/Details/5
        [CustomAuthorizeAttribute("Admin", "Doctor")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var doctorInfo = await _context.tblDoctor
                .FirstOrDefaultAsync(m => m.DoctorId == id);
            if (doctorInfo == null)
            {
                return NotFound();
            }

            return View(doctorInfo);
        }

        [CustomAuthorizeAttribute( "Doctor")]
        // GET: DoctorInfoes1/Create
        public IActionResult Create()
        {
            ViewData["DepartmentId"] = new SelectList(_context.tblDepartments, "DepartmentId", "DepartmentName");
            // ViewData["Id"] = new SelectList(_context.tblWeekDays, "Id", "DayName");
            var doctorInfo = new DoctorInfo();
            var weekdays = new Weekdays();

            doctorInfo.Weekdays = weekdays;
            return View(doctorInfo);
        }

        // POST: DoctorInfoes1/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DoctorId,IsAvailable,DepartmentId,DoctorFee,First_Name,Last_Name,EmailAddress,ContactNumber,HomeAddress")] DoctorInfo doctorInfo, Weekdays weekdays)
        {

            // Set the Weekdays property of the DoctorInfo object to the provided Weekdays object
            doctorInfo.Weekdays = weekdays;

            if (ModelState.IsValid)
            {
               // ViewData["DepartmentId"] = new SelectList(_context.tblDepartments, "DepartmentId", "DepartmentName", doctorInfo.DepartmentId);

                // Add the Weekdays object to the context and save changes
                _context.Add(weekdays);
                await _context.SaveChangesAsync();


                // Set the WeekdaysId property of the DoctorInfo object to the Weekdays object's primary key value
                doctorInfo.WeekdaysId = weekdays.WeekdaysId;


                //  ViewData["Id"] = new SelectList(_context.tblWeekDays, "Id", "DayName", );
                _context.Add(doctorInfo);
                await _context.SaveChangesAsync();

             
                    //if (Id != null)
                    //{
                    //    foreach (int id in Id)
                    //    {
                    //       Weekdays doctorWeekdays = new Weekdays
                    //        {
                    //           // DoctorId = doctorInfo.DoctorId,
                    //           // WeekdaysId = id
                    //        };
                    //        _context.Add(doctorWeekdays);
                    //    }
                    //    await _context.SaveChangesAsync();
                    //}






                    return RedirectToAction(nameof(Index));
            }


            ViewData["DepartmentId"] = new SelectList(_context.tblDepartments, "DepartmentId", "DepartmentName", doctorInfo.DepartmentId);
          //  ViewData["WeekdaysId"] = new SelectList(_context.tblWeekDays, "WeekdaysId", "DayName", Id);
           
            return View(doctorInfo);
        }

        // GET: DoctorInfoes1/Edit/5
        [CustomAuthorizeAttribute("Admin", "Doctor")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var doctorInfo = await _context.tblDoctor.FindAsync(id);
            if (doctorInfo == null)
            {
                return NotFound();
            }
            ViewData["DepartmentId"] = new SelectList(_context.tblDepartments, "DepartmentId", "DepartmentName", doctorInfo.DepartmentId);
            // var doct = new DoctorInfo();

            //var weekdays = new Weekdays();

            //doctorInfo.Weekdays = weekdays;
            var weekdays = await _context.tblWeekDays.FindAsync(doctorInfo.WeekdaysId);
            if (weekdays == null)
            {
                weekdays = new Weekdays();
            }

            // Map weekdays properties to DoctorInfo model
            doctorInfo.Weekdays = new Weekdays
            {
                Monday = weekdays.Monday,
                Tuesday = weekdays.Tuesday,
                Wednesday = weekdays.Wednesday,
                Thursday = weekdays.Thursday,
                Friday = weekdays.Friday,
                Saturday = weekdays.Saturday,
                Sunday = weekdays.Sunday
            };

            ViewData["DepartmentId"] = new SelectList(_context.tblDepartments, "DepartmentId", "DepartmentName", doctorInfo.DepartmentId);

            return View(doctorInfo);





           
        }

        // POST: DoctorInfoes1/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [CustomAuthorizeAttribute("Admin", "Doctor")]
        [HttpPost]
      
        [ValidateAntiForgeryToken]

DoctorAppointment/Views/Appointment/AppointmentDays.cshtml
@model IEnumerable<DoctorAppointment.Models.DoctorInfo>

@{
    Layout = null;
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>AppointmentDays</h1>

<p>
    @*<button asp-asp-controller="Appointment" asp-action="BookAppointment">NewAppointment</button>*@
    <button onclick=location.herf=@Url.Action("Appointment", "BookAppointment")'">New Appointment</button>

    
</p>
<table class="table">
    <thead>
        <tr>
           
            <th>
                @Html.DisplayNameFor(model => model.DoctorFee)
            </th>
            @*<th>
                @Html.DisplayNameFor(model => model.AvailableDates)
            </th>*@
            <th>
                @Html.DisplayNameFor(model => model.Department)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First_Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Last_Name)
            </th>
            
            
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
          
            <td>
                @Html.DisplayFor(modelItem => item.DoctorFee)
            </td>
            @*<td>
                @Html.DisplayFor(modelItem => item.AvailableDates)
            </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.Department.DepartmentName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.First_Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Last_Name)
            </td>
           
         
        </tr>
}
    </tbody>
</table>

DoctorAppointment/Views/Appointment/BookAppointment.cshtml
@using System.Web;
@using Microsoft.AspNetCore.Http;
<link href="~/css/bootstrap.min.css" rel="stylesheet" />
@{
    var Getrole = Context.Session.GetString("Role");
    if ( Getrole == "Patient")
    {

        Layout = "~/Views/Shared/Medicr_PatientLayout.cshtml";

    }

    else { 
        Layout = "~/Views/Shared/Medicr_Index.cshtml";
    }
    // Layout = null;
    // Layout = "~/Views/Shared/Medicr_Index.cshtml";
}
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
@*<link rel="stylesheet" href="~/DoctorAppointment.styles.css" asp-append-version="true" />*@
<link rel="stylesheet" href="~/css/bootstrap.min.css">

@*<script src="~/GettingRecordDoctors.js"></script>*@


@*<a href="@Url.Action("BookAppointment")" class="btn btn-primary">New Appointment</a>*@


<h1>Book Appointment By Days</h1>
<div class="modal" tabindex="-1" role="dialog" id="modal-form" style="border-block-color">
    <div class="modal-dialog modal-dialog-scrollable modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"> Doctors Information </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                @*View Return Display*@
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary">Save changes</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<!--<table class="table table-bordered table-dark table-striped">
    <tr>

        <td>
            <button class="btn-style-one rounded-pill" id="button1" value="@DateTime.Now.DayOfWeek">@DateTime.Now.DayOfWeek</button>
        </td>

        <td>

            <button class="btn-style-one rounded-pill" id="button2" value="@DateTime.Now.AddDays(1).DayOfWeek">@DateTime.Now.AddDays(1).DayOfWeek</button>
        </td>

        <td>

            <button class="btn-style-one rounded-pill" id="button3" value="@DateTime.Now.AddDays(2).DayOfWeek">@DateTime.Now.AddDays(2).DayOfWeek</button>
        </td>
    </tr>

    <tr>
        <td>
            <button class="btn-style-one rounded-pill" id="button4" value="@DateTime.Now.AddDays(3).DayOfWeek">@DateTime.Now.AddDays(3).DayOfWeek</button>
        </td>

        <td>
            <button class="btn-style-one rounded-pill" id="button5" value="@DateTime.Now.AddDays(4).DayOfWeek">@DateTime.Now.AddDays(4).DayOfWeek</button>
        </td>

        <td>
            <button class="btn-style-one rounded-pill" id="button6" value="@DateTime.Now.AddDays(5).DayOfWeek">@DateTime.Now.AddDays(5).DayOfWeek</button>
        </td>

    </tr>

    <tr>
        <td>
            <button class="btn-style-one rounded-pill" id="button7" value="@DateTime.Now.AddDays(6).DayOfWeek">@DateTime.Now.AddDays(6).DayOfWeek</button>
        </td>
    </tr>-->

    @*<tr>
            <td>
                <input type="text" id="textbox1" readonly>
            </td>
        </tr>*@

<!--</table>-->

<div id="availableDoctors"></div>

<table class="table table-bordered table-dark table-striped">
        <tr>

            <td>
                <button class="btn-style-one rounded-pill" id="button1" value="@DateTime.Now.Date.ToString("dd-MM-yyyy")">@DateTime.Now.DayOfWeek</button>
            </td>

            <td>

                <button class="btn-style-one rounded-pill" id="button2" value="@DateTime.Now.AddDays(1).Date.ToString("dd-MM-yyyy")">@DateTime.Now.AddDays(1).DayOfWeek</button>
            </td>

            <td>

                <button class="btn-style-one rounded-pill" id="button3" value="@DateTime.Now.AddDays(2).Date.ToString("dd-MM-yyyy")">@DateTime.Now.AddDays(2).DayOfWeek</button>
            </td>
        </tr>

        <tr>
            <td>
                <button class="btn-style-one rounded-pill" id="button4" value="@DateTime.Now.AddDays(3).Date.ToString("dd-MM-yyyy")">@DateTime.Now.AddDays(3).DayOfWeek</button>
            </td>

            <td>
                <button class="btn-style-one rounded-pill" id="button5" value="@DateTime.Now.AddDays(4).Date.ToString("dd-MM-yyyy")">@DateTime.Now.AddDays(4).DayOfWeek</button>
            </td>

            <td>
                <button class="btn-style-one rounded-pill" id="button6" value="@DateTime.Now.AddDays(5).Date.ToString("dd-MM-yyyy")">@DateTime.Now.AddDays(5).DayOfWeek</button>
            </td>

        </tr>

        <tr>
            <td>
                <button class="btn-style-one rounded-pill" id="button7"  value="@DateTime.Now.AddDays(6).Date.ToString("dd-MM-yyyy")">@DateTime.Now.AddDays(6).DayOfWeek</button>
            </td>
        </tr>

        <tr>
            <td>
                <input type="text" id="textbox1" readonly>
            </td>
        </tr>

    </table>

<h1>Book Appointment By Departments</h1>
<table class="table table-bordered table-dark table-striped">

    <tr>
        <td>
            @foreach (var department in ViewBag.Departments)
            {
                @*<a href="@Url.Action("Check", "Appointment", new { department = department })">
                        <button class="btn-success">@department</button>
                    </a>*@
                <button class="btn-style-one rounded-pill" onclick="OpenDepartment('@department')">@department</button>
            }
        </td>
    </tr>


    @*<tr>
            <td>
                <button class="btn-success" onclick="OpenDepartment(this.value)" value="1">Cardiology</button>
            </td>
            <td>
                <button class="btn-success" onclick="OpenDepartment(this.value)" value="2">Micro</button>
            </td>
            <td>
                <button class="btn-success" onclick="OpenDepartment(this.value)" value="3">Physiology</button>
            </td>
            <td>
                <button class="btn-success" onclick="OpenDepartment(this.value)" value="4">Emergency</button>
            </td>


        </tr>*@


</table>

@*<table class="table table-bordered table-dark table-striped">
        <tr>
            <td>
                <button class="btn-success" onclick="OpenDepartment(this.value)" value="1">Cardiology</button>
            </td>
            <td>
                <button class="btn-success" onclick="OpenDepartment(this.value)" value="2">Micro</button>
            </td>
            <td>
                <button class="btn-success" onclick="OpenDepartment(this.value)" value="3">Physiology</button>
            </td>
            <td>
                <button class="btn-success" onclick="OpenDepartment(this.value)" value="4">Emergency</button>
            </td>


        </tr>
    </table>*@


<script src="~/lib/jquery/dist/jquery.min.js"></script>

<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script>
    function OpenDepartment(department) {

        $.ajax({
            type: "GET",
            url: "/Appointment/Check",
            data: { department: department },
            success: function (result) //Pura view uth kr ajaiga Appointment/AppointmentDays"
            {
                $('#modal-form .modal-body').html(result);
                //alert(result);
                $('#modal-form').modal('show');

            }

        })
    }


    $(function () {
        $('#button1, #button2,#button3, #button4, #button5, #button6,  #button7').click(function () {
            var dayOfWeek = $(this).text();
            var dateOfWeek = $(this).val();

            //$(this).value().dayOfWeek.
        $.ajax({
            url: '@Url.Action("GetAvailableDoctors", "DoctorInfoes1")',
            type: 'GET',
            data: { dayOfWeek: dayOfWeek, dateOfWeek: dateOfWeek},
            success: function (result) {
                $('#modal-form .modal-body').html(result);
                $('#modal-form').modal('show');
            },
            error: function () {
                alert('An error occurred while getting the list of available doctors.');
            }
        });
    });
});



  //   $(document).ready(function() {
  //       $('#button1, #button2,#button3, #button4, #button5, #button6,  #button7').click(function() {
  //    var buttonValue = $(this).val();
  //    $('#textbox1').val(buttonValue);
  //  });
  //});










    function OpenPopup(Day) @*Ajax call javascript ja ander ajax call hogi *@
    {

        $.ajax({
            type:"GET",
            url:"/Appointment/AppointmentDays",
            data:{day:Day},
        success: function(result) //Pura view uth kr ajaiga Appointment/AppointmentDays"
            {
            $('#modal-form .modal-body').html(result);
            $('#modal-form').modal('show');
            }
        })
        }

</script>

DoctorAppointment/Views/Appointment/BookApppointmentByPatient.cshtml
@model DoctorAppointment.Models.Appointment

@{
    ViewData["Title"] = "BookApppointmentByPatient";
    Layout = "~/Views/Shared/Medicr_PatientLayout.cshtml";
}

<h1>BookApppointmentByPatient</h1>

<h4>Appointment</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="BookApppointmentByPatient">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="AppointmentDate" class="control-label"></label>
                <input asp-for="AppointmentDate" class="form-control" />
                <span asp-validation-for="AppointmentDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PatID" class="control-label"></label>
                <input value="ViewBag.PatId" class="form-control" />
                <span asp-validation-for="PatID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DocID" class="control-label"></label>
                <input asp-for="DocID" class="form-control" />
                <span asp-validation-for="DocID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AppointmentDay" class="control-label"></label>
                <input asp-for="AppointmentDay" class="form-control" />
                <span asp-validation-for="AppointmentDay" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

DoctorAppointment/Views/Appointment/Check.cshtml
@model IEnumerable<DoctorAppointment.Models.DoctorInfo>

@{
  Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Check</title>
</head>
<body>
    <div class="modal" tabindex="-1" role="dialog" id="modal-form">
        <div class="modal-dialog s" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    @*View Return Display*@
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary">Save changes</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
    @*<p>
            <a asp-action="Create">Create New</a>
        </p>*@


    @if (!Model.Any())
    {
        <p>   No doctors are available on that Department. </p>
    }

            else
            {

           
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.IsAvailable)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DoctorFee)
                </th>




                <th>
                    @Html.DisplayNameFor(model => model.First_Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Last_Name)
                </th>

                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.IsAvailable)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DoctorFee)
                    </td>
                    @*<td>
                            @Html.DisplayFor(modelItem => item.WeekdaysId)
                        </td>*@
                    <td>
                        @Html.DisplayFor(modelItem => item.First_Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Last_Name)
                    </td>

                    <td>
                        <a type="button" class="btn-style-one rounded-pill" asp-controller="PatientInfoes" asp-action="RegisterPatient"> Book_My_Appointment</a>
                        @*<button type="button" class="btn btn-primary" asp-controller="" asp-action="" onclick="location.href='@Url.Action("Edit", new { id = item.DoctorId })'">Book Appointment</button>*@

                    </td>
                </tr>
            }
        </tbody>
    </table>
    }
</body>
</html>

DoctorAppointment/Views/Appointment/DepartmentbyID.cshtml
@model IEnumerable<DoctorAppointment.Models.DoctorInfo>

@{
    Layout = null;
   // Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<h1>Appointment By Department</h1>

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>DepartmentbyID</title>
</head>
<body>
<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
           
            <th>
                @Html.DisplayNameFor(model => model.DoctorFee)
            </th>
           




            <th>
                @Html.DisplayNameFor(model => model.Department)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First_Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Last_Name)
            </th>
           
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
           
            <td>
                @Html.DisplayFor(modelItem => item.DoctorFee)
            </td>
           


            <td>
                @Html.DisplayFor(modelItem => item.Department.DepartmentName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.First_Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Last_Name)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.DoctorId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.DoctorId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.DoctorId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
</body>
</html>