DoctorAppointment/Models/UserLogin.cs
using System.ComponentModel.DataAnnotations;

namespace DoctorAppointment.Models
{
    public class UserLogin
    {
        [Key]
        public int ID { get; set; }
        public string LoginEmail { get; set; }

        public string Password { get; set; }

        public string UserRole { get; set; }
    }
}

DoctorAppointment/Controllers/UserLoginController.cs
using Microsoft.AspNetCore.Mvc;
using DoctorAppointment.Controllers;
using DoctorAppointment.Models;
using DoctorAppointment.Data;
using System.Linq;
using Microsoft.AspNetCore.Http;

namespace DoctorAppointment.Controllers
{
    public class UserLoginController : Controller
    {
        private readonly MyContext _context; //Local variabl
        public UserLoginController(MyContext context)
        {
            _context = context;
        }
        [HttpGet]
        public IActionResult Index()
        {
            UserLogin uselog= new UserLogin();
            return View();
        }
        [HttpPost]
        public IActionResult Index(UserLogin user)
        {
            var user1 = _context.tblUser.SingleOrDefault(m => m.LoginEmail == user.LoginEmail && m.Password == user.Password);

            if (user1 == null)
            {
                return View(user);
            }

            HttpContext.Session.SetString("Username", user.LoginEmail);
            HttpContext.Session.SetString("Password", user.Password);

            switch (user1.UserRole)
            {
                case "admin":
                    return RedirectToAction("Admin", "Admin");

                case "Patient":
                    return RedirectToAction("Create", "DoctorInfoes");

                default:
                    return RedirectToAction("BookAppointment", "Appointment");
            }
        }
        public IActionResult SuccessPage()
        {
            return View();
        }


        public IActionResult CustomLogin()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CustomLogin(UserLogin user)
        {
            var user1 = _context.tblUser.SingleOrDefault(m => m.LoginEmail == user.LoginEmail && m.Password == user.Password);
           // var userRole= user1.UserRole;
            if (user1 == null)
            {
                return View(user);
            }

            HttpContext.Session.SetString("UserEmail", user.LoginEmail);
            HttpContext.Session.SetString("Password", user.Password);

            switch (user1.UserRole)
            {
                case "Admin":
                    ViewBag.Role = "Admin";
                    TempData["Role"] = ViewBag.Role;
                    HttpContext.Session.SetString("Role", "Admin");
                    return RedirectToAction("Index", "DoctorInfoes1");

                case "Patient":
                    
                    ViewBag.Role = "Patient";
                    TempData["Role"] = ViewBag.Role;
                    HttpContext.Session.SetString("Role", "Patient");
                    return RedirectToAction("Index", "PatientInfoes");

                case "Doctor":
                    ViewBag.Role = "Doctor";
                    TempData["Role"] = ViewBag.Role;
                    HttpContext.Session.SetString("Role","Doctor");
                    return RedirectToAction("Index", "DoctorInfoes1");

                default:
                    return RedirectToAction("BookAppointment", "Appointment");
            }
           // return View();
        }


        public IActionResult CheckLayout()
        {
            return View();
        }

        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("CustomLogin");
        }

    }
}

DoctorAppointment/Views/UserLogin/CheckLayout.cshtml
@{
    //ViewData["Title"] = "CheckLayout";
    Layout = "~/Views/Shared/Medicr_Index.cshtml";
}

DoctorAppointment/Views/UserLogin/CustomLogin.cshtml
@model DoctorAppointment.Models.UserLogin
@{
    ViewData["Title"] = "CustomLogin";
    Layout = null;
    Layout = "~/Views/Shared/Medicr_Index.cshtml";



}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <link rel="stylesheet" href="~/assets/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/assets/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/assets/css/style.css" />
  
    <title>Educational Bootstrap 5 Login Page Website Tampalte</title>
</head>
<body>
    <section class="form-02-main">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="_lk_de">
                        <form method="post">
                            <div class="form-03-main">
                                <div class="logo">
                                    <img src="~/assets/images/user.png" />
                                </div>
                                <div class="form-group">
                                    <input asp-for="LoginEmail" class="form-control _ge_de_ol" type="email" placeholder="Enter Email" required aria-required="true" />
                                </div>

                                <div class="form-group">
                                    <input asp-for="Password" class="form-control _ge_de_ol" type="password" placeholder="Enter Password" required aria-required="true" />
                                </div>

                                <div class="checkbox form-group">
                                    <div class="form-check">
                                        <input class="form-check-input"  type="checkbox" value="true" id="rememberMe" />
                                        <label class="form-check-label" for="rememberMe">
                                            Remember me
                                        </label>
                                    </div>
                                    <a>Forgot Password</a>
                                </div>

                                <div class="form-group">
                                    <div class="">
                                        <button type="submit" class="_btn_04"> Login</button>
                                    </div>
                                </div>

                                <div class="form-group nm_lk"><p>Or Login With</p></div>

                                <div class="form-group pt-0">
                                    <div class="_social_04">
                                        <ol>
                                            <li><i class="fa fa-facebook"></i></li>
                                            <li><i class="fa fa-twitter"></i></li>
                                            <li><i class="fa fa-google-plus"></i></li>
                                            <li><i class="fa fa-instagram"></i></li>
                                            <li><i class="fa fa-linkedin"></i></li>
                                        </ol>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <script src="~/assets/js/bootstrap.min.js"></script>
</body>
</html>

DoctorAppointment/Views/UserLogin/Index.cshtml
@model DoctorAppointment.Models.UserLogin

@{
   
    ViewData["Title"] = "Index";
 
}
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
<link rel="stylesheet" href="~/DoctorAppointment.styles.css" asp-append-version="true" />

<h1>Index</h1>

<h4>Login</h4>
<hr />
<div class="row">
    <div class="col-md-4"  style="width:contain;padding:inherit;margin:auto;background-origin:initial">
        @using (Html.BeginForm("Index", "UserLogin", FormMethod.Post))
        {
            if (ViewBag.LoginStatus != null)
            {
                if (ViewBag.LoginStatus == 0)
                {
                    <div class="alert alert-danger">Invalid Login Detail</div>
                }
            }
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="LoginEmail" class="control-label"></label>
                @Html.TextAreaFor(m=>m.LoginEmail,new{@class="form-control",@placeholder="Email"})
                <span asp-validation-for="LoginEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                @Html.TextAreaFor(m=>m.Password,new{@class="form-control",@placeholder="Password"})
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserRole" class="control-label"></label>
                @Html.TextAreaFor(m=>m.UserRole,new{@class="form-control",@placeholder="User Role"})

                <span asp-validation-for="UserRole" class="text-danger"></span>
            </div>
            <br/>
            <div class="form-group">
                <input type="submit" value="Login" class="btn btn-primary" />
            </div>
            
        }
    </div>
</div>

<div>
   
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DoctorAppointment/Views/UserLogin/SuccessPage.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>Login Failed</h1>