DoctorAppointment/Controllers/PatientInfoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DoctorAppointment.Models;
using DoctorAppointment.Data;
using DoctorAppointment.Models.MVVM;
using Microsoft.AspNetCore.Http;

namespace DoctorAppointment.Controllers
{
   
    public class PatientInfoesController : Controller
    {
        private readonly MyContext _context;

        public PatientInfoesController(MyContext context)
        {
            _context = context;
        }

        // GET: PatientInfoes


        public IActionResult RegisterPatient()
        {
            return View();
            // Problem("Entity set 'MyContext.PatientInfo'  is null.");
        }

        [HttpPost]
        public IActionResult RegisterPatient(PatientVM model)
        {
            if (ModelState.IsValid)
            {
                var patient = new PatientInfo
                {
                    First_Name = model.FirstName,
                    Last_Name = model.LastName,
                    EmailAddress = model.PatientEmail
                };

                // Add the patient to the database
                _context.tblPatients.Add(patient);
                _context.SaveChanges();

                // Create a new UserLogin object
                var user = new UserLogin
                {
                    LoginEmail = model.PatientEmail,
                    Password = model.Password,
                    UserRole = "Patient"
                };

                // Add the user to the database
                _context.tblUser.Add(user);
                _context.SaveChanges();

                // Do something with the validated model data
                // e.g. save it to the database

                // Redirect to a success page
                return RedirectToAction("CustomLogin", "UserLogin");
            }

            // If the model state is not valid, return the view with the invalid model
            return View(model);
        }

        [CustomAuthorizeAttribute("Admin", "Doctor", "Patient")]
        public IActionResult Index()
        {

            string UserRole = HttpContext.Session.GetString("Role");

            if (UserRole == "Patient")
            {
                string userEmail = HttpContext.Session.GetString("UserEmail");
                var patient =  _context.tblPatients.Where(p => p.EmailAddress == userEmail);

                var pateintid = patient.FirstOrDefault().PatientId;
               
              HttpContext.Session.SetString("Patient", pateintid.ToString());
                return View(patient);
            }

            else { 

            return View(_context.tblPatients.ToList());

            }
            // Problem("Entity set 'MyContext.PatientInfo'  is null.");
        }

        [CustomAuthorizeAttribute("Admin", "Doctor", "Patient")]
        // GET: PatientInfoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.tblPatients == null)
            {
                return NotFound();
            }

            var patientInfo = await _context.tblPatients
                .FirstOrDefaultAsync(m => m.PatientId == id);
            if (patientInfo == null)
            {
                return NotFound();
            }

            return View(patientInfo);
        }

        // GET: PatientInfoes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: PatientInfoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [CustomAuthorizeAttribute("Admin","Patient")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PatientId,PatientHistory,First_Name,Last_Name,EmailAddress,ContactNumber,HomeAddress")] PatientInfo patientInfo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(patientInfo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(patientInfo);
        }

        [CustomAuthorizeAttribute("Admin", "Patient")]
        // GET: PatientInfoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.tblPatients == null)
            {
                return NotFound();
            }

            var patientInfo = await _context.tblPatients.FindAsync(id);
            if (patientInfo == null)
            {
                return NotFound();
            }
            return View(patientInfo);
        }

        // POST: PatientInfoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [CustomAuthorizeAttribute("Admin", "Patient")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PatientId,PatientHistory,First_Name,Last_Name,EmailAddress,ContactNumber,HomeAddress")] PatientInfo patientInfo)
        {
            if (id != patientInfo.PatientId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(patientInfo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PatientInfoExists(patientInfo.PatientId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(patientInfo);
        }

        // GET: PatientInfoes/Delete/5
        [CustomAuthorizeAttribute("Admin", "Patient")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.tblPatients == null)
            {
                return NotFound();
            }

            var patientInfo = await _context.tblPatients
                .FirstOrDefaultAsync(m => m.PatientId == id);
            if (patientInfo == null)
            {
                return NotFound();
            }

            return View(patientInfo);
        }

        // POST: PatientInfoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [CustomAuthorizeAttribute("Admin","Patient")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.tblPatients == null)
            {
                return Problem("Entity set 'MyContext.PatientInfo'  is null.");
            }
            var patientInfo = await _context.tblPatients.FindAsync(id);
            if (patientInfo != null)
            {
                _context.tblPatients.Remove(patientInfo);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PatientInfoExists(int id)
        {
          return (_context.tblPatients?.Any(e => e.PatientId == id)).GetValueOrDefault();
        }

       




       // [HttpPost]
        public IActionResult BookApppointmentByPatient(int? id)
        {
           var role =HttpContext.Session.GetString("Role");

            if (role == null)
            {
                return RedirectToAction("RegisterPatient");
            }
            

            else
            {
                // code to retrieve the day of week
                ViewBag.dayofweek = HttpContext.Session.GetString("dayofweek");
                ViewBag.PTID = HttpContext.Session.GetString("Patient");
                ViewBag.Date = HttpContext.Session.GetString("dateofweek");
                ViewBag.Doctor = id;
                // create the model and set the AppointmentDay property
                var model = new Appointment();
                model.AppointmentDay = ViewBag.dayofweek;
                model.DocID = ViewBag.Doctor;
                model.AppointmentDate = ViewBag.Date;
                model.PatID = Int32.Parse(ViewBag.PTID);
                // model.PatID = ViewBag.PTID;
                return View(model);






               // ViewBag.dayofweek = HttpContext.Session.GetString("dayofweek");
              //   = dayofweek;
              //  ViewBag.PTID =  HttpContext.Session.GetString("Patient");
               // ViewBag.Doctor = id;
               // ViewBag.Pat = HttpContext.Session.GetString("PtID");
              //  return View();
            }
        }
    }
}

DoctorAppointment/Views/PatientInfoes/BookApppointmentByPatient.cshtml
@using System.Web;
@using Microsoft.AspNetCore.Http;

@model DoctorAppointment.Models.Appointment
<script src="~/GettingRecordDoctors.js"></script>
@{
    ViewData["Title"] = "BookApppointmentByPatient";
    Layout = "~/Views/Shared/Medicr_PatientLayout.cshtml";
  //  Model.AppointmentDay = @ViewBag.dayofweek;
   // Model.AppointmentDay =
}

<h1>BookApppointmentByPatient</h1>

<h4>Appointment</h4>
<hr />
@*<table class="table table-bordered table-dark table-striped">
    <tr>

        <td>
            <button class="btn-success" id="button1" value="@DateTime.Now.Date.ToString("dd-MM-yyyy")">@DateTime.Now.DayOfWeek</button>
        </td>

        <td>

            <button class="btn-success" id="button2" value="@DateTime.Now.AddDays(1).Date.ToString("dd-MM-yyyy")">@DateTime.Now.AddDays(1).DayOfWeek</button>
        </td>

        <td>

            <button class="btn-success" id="button3" value="@DateTime.Now.AddDays(2).Date.ToString("dd-MM-yyyy")">@DateTime.Now.AddDays(2).DayOfWeek</button>
        </td>
    </tr>

    <tr>
        <td>
            <button class="btn-success" id="button4" value="@DateTime.Now.AddDays(3).Date.ToString("dd-MM-yyyy")">@DateTime.Now.AddDays(3).DayOfWeek</button>
        </td>

        <td>
            <button class="btn-success" id="button5" value="@DateTime.Now.AddDays(4).Date.ToString("dd-MM-yyyy")">@DateTime.Now.AddDays(4).DayOfWeek</button>
        </td>

        <td>
            <button class="btn-success" id="button6" value="@DateTime.Now.AddDays(5).Date.ToString("dd-MM-yyyy")">@DateTime.Now.AddDays(5).DayOfWeek</button>
        </td>

    </tr>

    <tr>
        <td>
            <button class="btn-success" id="button7" value="@DateTime.Now.AddDays(6).Date.ToString("dd-MM-yyyy")">@DateTime.Now.AddDays(6).DayOfWeek</button>
        </td>
    </tr>

    <tr>
        <td>
            <input type="text" id="textbox1" readonly>
        </td>
    </tr>
</table>*@

<div class="row">
    <div class="col-md-4">



        <form asp-action="Add" asp-controller="Appointment">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                    <label asp-for="AppointmentDate" class="control-label"></label>
                    <input asp-for="AppointmentDate" class="form-control" readonly />
                    <span asp-validation-for="AppointmentDate" class="text-danger"></span>
                </div>
            <div class="form-group">
                <label asp-for="PatID" class="control-label"></label>
                <input asp-for="PatID" class="form-control" readonly />
                <span asp-validation-for="PatID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DocID" class="control-label"></label>
                <input asp-for="DocID"  class="form-control" readonly />
                @*<input asp-for="DocID" value="@ViewBag.Doctor" class="form-control" readonly />*@
                <span asp-validation-for="DocID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AppointmentDay" class="control-label"></label>
                <input asp-for="AppointmentDay"  class="form-control"  readonly/>
                <span asp-validation-for="AppointmentDay" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

<script src="~/lib/jquery/dist/jquery.min.js"></script>

<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        $('#button1,#button2,#button3,#button4,#button5,#button6,#button7').click(function () {
            alert()
            var buttonValue = $(this).val();
            $('#AppointmentDate').val(buttonValue);
        });
    });



</script>

DoctorAppointment/Views/PatientInfoes/Create.cshtml
@model DoctorAppointment.Models.PatientInfo

@{
    ViewData["Title"] = "Create";
   // Layout = null;
}


<h1>Create</h1>

<h4>PatientInfo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PatientHistory" class="control-label"></label>
                <input asp-for="PatientHistory" class="form-control" />
                <span asp-validation-for="PatientHistory" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="First_Name" class="control-label"></label>
                <input asp-for="First_Name" class="form-control" />
                <span asp-validation-for="First_Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Last_Name" class="control-label"></label>
                <input asp-for="Last_Name" class="form-control" />
                <span asp-validation-for="Last_Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmailAddress" class="control-label"></label>
                <input asp-for="EmailAddress" class="form-control" />
                <span asp-validation-for="EmailAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContactNumber" class="control-label"></label>
                <input asp-for="ContactNumber" class="form-control" />
                <span asp-validation-for="ContactNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HomeAddress" class="control-label"></label>
                <input asp-for="HomeAddress" class="form-control" />
                <span asp-validation-for="HomeAddress" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label for="appointment-day">Appointment Day</label>
                <div class="btn-group" role="group" aria-label="Appointment Day">
                    <button class="btn-success" id="button1" value="@DateTime.Now.Date.ToString("dd-MM-yyyy")">@DateTime.Now.DayOfWeek</button>
                    <button class="btn-success" id="button2" value="@DateTime.Now.AddDays(1).Date.ToString("dd-MM-yyyy")">@DateTime.Now.AddDays(1).DayOfWeek</button>
                    <button class="btn-success" id="button3" value="@DateTime.Now.AddDays(2).Date.ToString("dd-MM-yyyy")">@DateTime.Now.AddDays(2).DayOfWeek</button>
                    <button class="btn-success" id="button4" value="@DateTime.Now.AddDays(3).Date.ToString("dd-MM-yyyy")">@DateTime.Now.AddDays(3).DayOfWeek</button>
                    <button class="btn-success" id="button5" value="@DateTime.Now.AddDays(4).Date.ToString("dd-MM-yyyy")">@DateTime.Now.AddDays(4).DayOfWeek</button>
                    <button class="btn-success" id="button6" value="@DateTime.Now.AddDays(5).Date.ToString("dd-MM-yyyy")">@DateTime.Now.AddDays(5).DayOfWeek</button>
                    <button class="btn-success" id="button7" value="@DateTime.Now.AddDays(6).Date.ToString("dd-MM-yyyy")">@DateTime.Now.AddDays(6).DayOfWeek</button>



                    @*<button type="button" class="btn btn-secondary appointment-day-btn" data-day="Tuesday">Tue</button>
                    <button type="button" class="btn btn-secondary appointment-day-btn" data-day="Wednesday">Wed</button>
                    <button type="button" class="btn btn-secondary appointment-day-btn" data-day="Thursday">Thu</button>
                    <button type="button" class="btn btn-secondary appointment-day-btn" data-day="Friday">Fri</button>
                    <button type="button" class="btn btn-secondary appointment-day-btn" data-day="Saturday">Sat</button>
                    <button type="button" class="btn btn-secondary appointment-day-btn" data-day="Sunday">Sun</button>*@
                </div>
                <input type="text"  id="appointment-day" value="" >
            </div>




            <br />
            <div class="form-group mb-xl-auto">
                <a href="~/BookAppointment/Appointment" value="Create" class="btn btn-primary">Skip Add new patient</a>
                <input type="submit" value="Create" class="btn btn-primary" />

            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

<script>

//    const { Script } = require("vm");



     $(document).ready(function() {
         $('#button1, #button2,#button3, #button4, #button5, #button6,  #button7').click(function() {
      var buttonValue = $(this).val();
             $('#appointment-day').val(buttonValue);
    });
  });

</script>

DoctorAppointment/Views/PatientInfoes/Delete.cshtml
@model DoctorAppointment.Models.PatientInfo

@{
    ViewData["Title"] = "Delete";
   // Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PatientInfo</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PatientHistory)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PatientHistory)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.First_Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.First_Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Last_Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Last_Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EmailAddress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EmailAddress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ContactNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ContactNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HomeAddress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HomeAddress)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="PatientId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

DoctorAppointment/Views/PatientInfoes/Details.cshtml
@model DoctorAppointment.Models.PatientInfo

@{
    ViewData["Title"] = "Details";
   // Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>PatientInfo</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PatientHistory)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PatientHistory)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.First_Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.First_Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Last_Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Last_Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EmailAddress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EmailAddress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ContactNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ContactNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HomeAddress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HomeAddress)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.PatientId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

DoctorAppointment/Views/PatientInfoes/Edit.cshtml
@model DoctorAppointment.Models.PatientInfo

@{
    ViewData["Title"] = "Edit";
  //  Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Edit</h1>

<h4>PatientInfo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="PatientId" />
            <div class="form-group">
                <label asp-for="PatientHistory" class="control-label"></label>
                <input asp-for="PatientHistory" class="form-control" />
                <span asp-validation-for="PatientHistory" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="First_Name" class="control-label"></label>
                <input asp-for="First_Name" class="form-control" />
                <span asp-validation-for="First_Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Last_Name" class="control-label"></label>
                <input asp-for="Last_Name" class="form-control"  />
                <span asp-validation-for="Last_Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmailAddress" class="control-label"></label>
                <input asp-for="EmailAddress" class="form-control" readonly/>
                <span asp-validation-for="EmailAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContactNumber" class="control-label"></label>
                <input asp-for="ContactNumber" class="form-control" />
                <span asp-validation-for="ContactNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HomeAddress" class="control-label"></label>
                <input asp-for="HomeAddress" class="form-control" />
                <span asp-validation-for="HomeAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

DoctorAppointment/Views/PatientInfoes/Index.cshtml
@using System.Web;
@using Microsoft.AspNetCore.Http;

@model IEnumerable<DoctorAppointment.Models.PatientInfo>

@{
    ViewData["Title"] = "Index";
    //  Layout = "~/Views/Shared/_AdminLayout.cshtml";
    var pt = Context.Session.GetString("Patient");
}


<h1>Index</h1>

<p>

</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PatientHistory)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First_Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Last_Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EmailAddress)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ContactNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HomeAddress)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.PatientHistory)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.First_Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Last_Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EmailAddress)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ContactNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.HomeAddress)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.PatientId" class="btn btn-primary">Edit</a>
                    @*<a asp-action="Edit" asp-route-id="@item.PatientId">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.PatientId">Details</a> |*@
                    <a asp-action="Delete" asp-route-id="@item.PatientId" class="btn btn-danger">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

DoctorAppointment/Views/PatientInfoes/Register.cshtml
@model DoctorAppointment.Models.PatientInfo

@{
    Layout = null;
    Layout = "~/Views/Shared/Medicr_Index.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Register</title>
</head>
<body>

<h4>PatientInfo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PatientHistory" class="control-label"></label>
                <input asp-for="PatientHistory" class="form-control" />
                <span asp-validation-for="PatientHistory" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="First_Name" class="control-label"></label>
                <input asp-for="First_Name" class="form-control" />
                <span asp-validation-for="First_Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Last_Name" class="control-label"></label>
                <input asp-for="Last_Name" class="form-control" />
                <span asp-validation-for="Last_Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmailAddress" class="control-label"></label>
                <input asp-for="EmailAddress" class="form-control" />
                <span asp-validation-for="EmailAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContactNumber" class="control-label"></label>
                <input asp-for="ContactNumber" class="form-control" />
                <span asp-validation-for="ContactNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HomeAddress" class="control-label"></label>
                <input asp-for="HomeAddress" class="form-control" />
                <span asp-validation-for="HomeAddress" class="text-danger"></span>
            </div>


           

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
</body>
</html>

DoctorAppointment/Views/PatientInfoes/RegisterPatient.cshtml
@model DoctorAppointment.Models.MVVM.PatientVM
@{
    Layout = "~/Views/Shared/Medicr_Index.cshtml";
}

<h1 style="text-align: center;"> Patient Registration </h1>


<hr />

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-4">
            <form asp-action="RegisterPatient" asp-controller="PatientInfoes">
                <div class="form-group">
                    <label asp-for="FirstName"> First Name</label>
                    <input asp-for="FirstName"  placeholder="Enter FirstName" class="form-control rounded-pill" required>
                </div>
                <div class="form-group">
                    <label asp-for="LastName">Last Name</label>
                    <input asp-for="LastName" type="text"  placeholder="Enter LastName" class="form-control rounded-pill" required>
                </div>
                <div class="form-group">
                    <label asp-for="PatientEmail">Email </label>
                    <input asp-for="PatientEmail" type="email" placeholder="Enter Your Email" class="form-control rounded-pill" required>
                </div>
                <div class="form-group">
                    <label asp-for="Password"> Password</label>
                    <input asp-for="Password" type="password" placeholder="Enter Password" class="form-control rounded-pill" required>
                </div>
                <div class="form-group">
                    <input type="submit" value="Register" class="btn btn-primary rounded-pill" />
                </div>
            </form>
        </div>

    </div>

    </div>